package javaCC.part1;
/* Generated By:JavaCC: Do not edit this line. ExampleParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_CONSTANT = 6;
  /** RegularExpression Id. */
  int LOGIC_CONSTANT = 7;
  /** RegularExpression Id. */
  int STRING_CONSTANT = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int END = 12;
  /** RegularExpression Id. */
  int SUB = 13;
  /** RegularExpression Id. */
  int LET = 14;
  /** RegularExpression Id. */
  int CALL = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int CASE = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int INPUT = 19;
  /** RegularExpression Id. */
  int PRINT = 20;
  /** RegularExpression Id. */
  int SELECT = 21;
  /** RegularExpression Id. */
  int STATIC = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;
  /** RegularExpression Id. */
  int LETTER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<INTEGER_CONSTANT>",
    "<LOGIC_CONSTANT>",
    "<STRING_CONSTANT>",
    "<DIGIT>",
    "\"not\"",
    "\"if\"",
    "\"end\"",
    "\"sub\"",
    "\"let\"",
    "\"call\"",
    "\"then\"",
    "\"case\"",
    "\"else\"",
    "\"input\"",
    "\"print\"",
    "\"select\"",
    "\"static\"",
    "<IDENTIFIER>",
    "<LETTER>",
  };

}
